name: sound
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=22.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=1.2.0
  - fftw=3.3.9
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.10.4
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.19.4
  - ipython=8.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.14
  - jsonschema=4.16.0
  - jupyter_client=7.4.8
  - jupyter_core=5.1.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.2
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openpyxl=3.0.9
  - openssl=1.1.1u
  - packaging=22.0
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=21.2.4
  - platformdirs=2.6.0
  - plotly=5.13.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.13.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytz=2022.1
  - pywin32=305
  - pywinpty=2.0.2
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - requests=2.31.0
  - scipy=1.9.3
  - send2trash=1.8.0
  - setuptools=61.2.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.38.5
  - stack_data=0.6.2
  - tenacity=8.0.1
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.8.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022a
  - urllib3=2.0.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xlrd=2.0.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - import-ipynb==0.1.4
    - nbimport==0.0.0